---
version: "3"
services:
    impf-bot:
        image: pfuenzle/impf-bot
        container_name: impf-bot
        volumes:
            - ./config.properties:/app/src/main/resources/config.properties
        restart: unless-stopped
    
