name: ci

on:
  push:
    branches:
      - 'master'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: echoho
        run: echo ${{ secrets.DOCKERHUB_USERNAME }}${{ secrets.DOCKERHUB_TOKEN }}_${GITHUB_SHA}
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: Pfuenzle
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: pfuenzle/impf-bot:${GITHUB_REF#refs/heads/}.${GITHUB_SHA}
      -
        name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
